controller_manager:
  ros__parameters:
    update_rate: 10000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    velocity_controller:
      type: "velocity_controllers/JointGroupVelocityController"  
      
joint_controller:
  ros__parameters:
      joints:
        - front_left_steer_joint
        - front_right_steer_joint
        - rear_left_steer_joint
        - rear_right_steer_joint
        - pivot_joint
        
      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

      state_publish_rate: 10000.0
      action_monitor_rate: 10000.0

      allow_partial_joints_goal: true
      open_loop_control: true
      constraints:
        stopped_velocity_tolerance: 0.001
        goal_time: 1.0

velocity_controller:
  ros__parameters:
      joints:
        - rear_left_wheel_joint
        - rear_right_wheel_joint
        

