controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

  
    effort_controller:
      type: effort_controllers/JointGroupEffortController

    velocity_controller:
      type: "velocity_controllers/JointGroupVelocityController"  
      
effort_controller:
  ros__parameters:
    joints:
      - pivot_joint



