controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster


    wheel_controller:
      type: effort_controllers/JointGroupEffortController

    steer_controller:
      type: effort_controllers/JointGroupEffortController

      
wheel_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

steer_controller:
  ros__parameters:
    joints:
      - front_left_steer_joint
      - front_right_steer_joint
      - rear_left_steer_joint
      - rear_right_steer_joint
      - pivot_joint



