controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: "position_controllers/JointGroupPositionController" 

    velocity_controller:
      type: "velocity_controllers/JointGroupVelocityController"  
   
position_controller:
  ros__parameters:
      joints:
        - front_left_steer_joint
        - front_right_steer_joint
        - rear_left_steer_joint
        - rear_right_steer_joint
        - pivot_joint
      gains :
        front_left_steer_joint: {p: 0.0, i: 0.0, d: 0.0}   
        front_right_steer_joint: {p: 0.0, i: 0.0, d: 0.0} 
        rear_left_steer_joint: {p: 0.0, i: 0.0, d: 0.0} 
        rear_right_steer_joint: {p: 0.0, i: 0.0, d: 0.0} 
        pivot_joint: {p: 0.0, i: 0.0, d: 0.0} 


velocity_controller:
  ros__parameters:
      joints:
        - front_left_wheel_joint
        - front_right_wheel_joint
        - rear_left_wheel_joint
        - rear_right_wheel_joint
      gains :
        rear_left_wheel_joint: {p: 0.0, i: 0.0, d: 0.0}   
        rear_right_wheel_joint: {p: 0.0, i: 0.0, d: 0.0} 
        front_left_wheel_joint: {p: 0.0, i: 0.0, d: 0.0}   
        front_right_wheel_joint: {p: 0.0, i: 0.0, d: 0.0} 


