controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    position_controller:
      type: "position_controllers/JointGroupPositionController" 

    velocity_controller:
      type: "velocity_controllers/JointGroupVelocityController"  
   
position_controller:
  ros__parameters:
      joints:
        - front_left_steer_joint
        - front_right_steer_joint
        - rear_left_steer_joint
        - rear_right_steer_joint
        - pivot_joint


velocity_controller:
  ros__parameters:
      joints:
        - front_left_wheel_joint
        - front_right_wheel_joint
        - rear_left_wheel_joint
        - rear_right_wheel_joint
    

joint_state:
  ros__parameters:
      joints:
        - bogie_joint


