<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ernest">
  <xacro:include filename="inertial_macros.xacro"/>

  <xacro:property name="body_width" value="0.318"/>
  <xacro:property name="body_length" value="0.436"/>
  <xacro:property name="chassis_thickness" value="0.056"/>
  <xacro:property name="chassis_height" value="0.05"/>
  <xacro:property name="middle_chassis_length" value="${(body_length - chassis_thickness)/2}"/>

  <xacro:property name="wheel_width" value="0.06" />
  <xacro:property name="wheel_radius" value="0.1" />
  
  
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
  </material>

  <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
  </material>

  <material name="black">
      <color rgba="0 0 0 1"/>
  </material>

<!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
    </collision>    

    <xacro:inertial_box mass="0.5" x="${chassis_thickness}" y="${body_width}" z="${chassis_height}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>

  </link>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>
 
<!-- CHASSIS --> 
    <!-- REAR PART --> 
  <link name="back_chassis">
    <visual>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </visual>

    <collision>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </collision>

    <xacro:inertial_box mass="0.5" x="${middle_chassis_length}" y="${chassis_thickness}" z="${chassis_height}">
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>   
    </xacro:inertial_box>
    
  </link>

  <gazebo reference="back_chassis">
    <material>Gazebo/White</material>
  </gazebo>

    <!-- REAR WELDING --> 
  <joint name="front_attatch" type="fixed">
    <parent link="base_link"/>
    <child link="back_chassis"/>
    <origin xyz="${chassis_thickness/-2} 0 0"/>
  </joint>


    <!-- MIDDLE PART --> 
  <link name="middle_chassis">
    <visual>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </collision>

    <xacro:inertial_box mass="0.5" x="${middle_chassis_length}" y="${chassis_thickness}" z="${chassis_height}">
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>   
    </xacro:inertial_box>
  </link>

  <gazebo reference="middle_chassis">
    <material>Gazebo/White</material>
  </gazebo>

    <!-- STEERING JOINT --> 
  <joint name="steering_joint" type="revolute">
    <axis xyz="0 0 -1"/>
    <limit effort="50" lower="-1.571" upper="1.571" velocity="30"/>
    <parent link="back_chassis"/>
    <child link="middle_chassis"/>
    <origin xyz="${-1*middle_chassis_length} 0 0"/>
  </joint>

    <!-- FRONT PART --> 
  <link name="front_chassis">
    <visual>
      <geometry>
        <box size=" ${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size=" ${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 0"/>
    </collision>

    <xacro:inertial_box mass="0.5" x="${chassis_thickness}" y="${body_width}" z="${chassis_height}">
      <origin xyz="0 0 0"/>  
    </xacro:inertial_box>
  </link>
  <gazebo reference="front_chassis">
    <material>Gazebo/White</material>
  </gazebo>

    <!-- BOOGIE JOINT --> 
  <joint name="bogie_joint" type="revolute">
    <axis xyz="-1 0 0"/>
    <limit effort="50" lower="-1.571" upper="1.571" velocity="30"/>
    <parent link="middle_chassis"/>
    <child link="front_chassis"/>
    <origin xyz="${body_length/-2} 0 0"/>
  </joint>

<!-- WHEELS-->
  <xacro:macro name="wheel" params="wheel_prefix flip parent *joint_pose">

    <link name="${wheel_prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${flip*pi/2}" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${flip*pi/2}" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.5" length="${wheel_width}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${flip*pi/2}" /> 
      </xacro:inertial_cylinder>
    </link>

  <gazebo reference="{wheel_prefix}_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>

    <!-- rolling -->
    <joint name="${wheel_prefix}_wheel" type="continuous">
      <parent link="${parent}"/>
      <child link="${wheel_prefix}_wheel_link"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>

    <!-- steering -->
    <joint name="${wheel_prefix}_wheel_steer" type="revolute">
      <limit effort="50" lower="-1.571" upper="1.571" velocity="30"/>
      <parent link="${parent}"/>
      <child link="${wheel_prefix}_wheel_link"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 0 -1" rpy="0 0 0" />
    </joint>


  </xacro:macro>


  <xacro:wheel wheel_prefix="front_left" flip="-1" parent="front_chassis">
    <origin xyz="0 ${-body_width/2} -.009" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="front_right" flip="1" parent="front_chassis">
    <origin xyz="0 ${body_width/2} -.009" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="rear_left" flip="-1" parent="base_link">
    <origin xyz="0 ${-body_width/2} -.009" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="rear_right" flip="1" parent="base_link">
    <origin xyz="0 ${body_width/2} -.009" rpy="0 0 0" />
  </xacro:wheel>


</robot>