<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ernest_lowpoly">

<xacro:macro name="robot_core" params="prefix">
  <xacro:include filename="inertial_macros.xacro"/>

  <xacro:property name="body_width" value="0.318"/>
  <xacro:property name="body_length" value="0.436"/>
  <xacro:property name="chassis_thickness" value="0.056"/>
  <xacro:property name="chassis_height" value="0.05"/>
  <xacro:property name="middle_chassis_length" value="${(body_length - chassis_thickness)/2}"/>

  <xacro:property name="wheel_width" value="0.06" />
  <xacro:property name="wheel_radius" value="0.1" />
  
  
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
  </material>

  <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
  </material>

  <material name="black">
      <color rgba="0 0 0 1"/>
  </material>

  <link name="${prefix}base_link">
  </link>

  <joint name="${prefix}frame_joint" type="fixed">
    <origin  xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint> 
<!-- BASE LINK -->
  <link name="${prefix}chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
    </collision>    

    <xacro:inertial_box mass="0.5" x="${chassis_thickness}" y="${body_width}" z="${chassis_height}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>

  </link>

<!-- CHASSIS --> 
    <!-- REAR PART --> 
  <link name="${prefix}back_chassis">
    <visual>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </visual>

    <collision>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </collision>

    <xacro:inertial_box mass="0.5" x="${middle_chassis_length}" y="${chassis_thickness}" z="${chassis_height}">
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>   
    </xacro:inertial_box>
    
  </link>

    <!-- REAR WELDING --> 
  <joint name="${prefix}front_attatch" type="fixed">
    <parent link="chassis"/>
    <child link="back_chassis"/>
    <origin xyz="${chassis_thickness/-2} 0 0"/>
  </joint>


    <!-- MIDDLE PART --> 
  <link name="${prefix}pivot">
    <visual>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${middle_chassis_length} ${chassis_thickness} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>
    </collision>

    <xacro:inertial_box mass="0.5" x="${middle_chassis_length}" y="${chassis_thickness}" z="${chassis_height}">
      <origin rpy="0 0 0" xyz="${middle_chassis_length/-2} 0 0"/>   
    </xacro:inertial_box>
  </link>


    <!-- STEERING JOINT --> 
  <joint name="${prefix}pivot_joint" type="revolute">
    <axis xyz="0 0 -1"/> 
    <limit effort="50" lower="-1.571" upper="1.571" velocity="30"/>
    <parent link="back_chassis"/> 
    <child link="pivot"/>
    <origin xyz="${-1*middle_chassis_length} 0 0"/>
  </joint>

    <!-- FRONT PART --> 
  <link name="${prefix}bogie">
    <visual>
      <geometry>
        <box size=" ${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size=" ${chassis_thickness} ${body_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 0"/>
    </collision>

    <xacro:inertial_box mass="0.5" x="${chassis_thickness}" y="${body_width}" z="${chassis_height}">
      <origin xyz="0 0 0"/>  
    </xacro:inertial_box>
  </link>


    <!-- BOOGIE JOINT --> 
  <joint name="${prefix}bogie_joint" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="50" lower="-1.571" upper="1.571" velocity="30"/>
    <parent link="pivot"/>
    <child link="bogie"/>
    <origin xyz="${body_length/-2} 0 0" rpy="0 ${-pi/2} 0"/>
  </joint>

<!-- WHEELS-->
  <xacro:macro name="wheel" params="wheel_prefix flip parent *joint_pose">

    <link name="${wheel_prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${flip*pi/2}" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${flip*pi/2}" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.5" length="${wheel_width}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 ${flip*pi/2}" /> 
      </xacro:inertial_cylinder>
    </link>

    <!-- steering -->
    <joint name="${wheel_prefix}_wheel_steer" type="revolute">
      <limit effort="50" lower="-1.571" upper="1.571" velocity="30"/> 
      <parent link="${parent}"/>
      <child link="${wheel_prefix}_wheel"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 0 -1" rpy="0 0 0" />
    </joint>
    
    <!-- rolling -->
    <joint name="${wheel_prefix}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${wheel_prefix}_wheel"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 0 1" rpy="0 0 0" />
    </joint>

  </xacro:macro>


  <xacro:wheel wheel_prefix="${prefix}front_left" flip="-1" parent="${prefix}bogie">
    <origin xyz="0 ${-body_width/2} -.009" rpy="${pi/2} 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="${prefix}front_right" flip="1" parent="${prefix}bogie">
    <origin xyz="0 ${body_width/2} -.009" rpy="${pi/2} 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="${prefix}rear_left" flip="-1" parent="${prefix}chassis">
    <origin xyz="0 ${-body_width/2} -.009" rpy="${pi/2} 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="${prefix}rear_right" flip="1" parent="${prefix}chassis">
    <origin xyz="0 ${body_width/2} -.009" rpy="${pi/2} 0 0" />
  </xacro:wheel>


</xacro:macro>
</robot>